export const FILL_BLOG_DATA = "FILL_BLOG_DATA";
export const FILL_BLOG_DATA_LOADING = "FILL_BLOG_DATA_LOADING";
export const FILL_BLOG_DATA_ERROR = "FILL_BLOG_DATA_ERROR";
export const FILL_USER_DATA = "FILL_USER_DATA";
export const FILL_USER_DATA_LOADING = "FILL_USER_DATA_LOADING";
export const FILL_USER_DATA_ERROR = "FILL_USER_DATA_ERROR";